services:
  db:
    container_name: postgres_database
    image: postgres:15.10-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-db:
    external: false